[build]
  publish = "exampleSite/public"
  command = "cd ./exampleSite && hugo --gc --minify --themesDir ../ --layoutDir ../layouts "


  [build.environment]
    HUGO_VERSION = "0.121"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -s exampleSite --minify -D -F -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -s exampleSite --minify --gc -b $DEPLOY_PRIME_URL"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"
