# Interface sveltia, utilisé avec auth.js/supabase, avec ingredients dans /content (implique un md par ingredient)

backend:
  name: github
  repo: encas-parka/enka-cookbook-site
  branch: final-ingmig
  base_url: https://enka-cookbook.pages.dev
  logout_redirect_url: https://enka-cookbook.pages.dev/
  auth_type: github
  automatic_deployments: false

  # Vérifier si ca marche bien : si un article est modifier plusieur fois avant d'etre mergé/publié, un seul commit avec rebased.
  squash_merges: true

media_folder: ""
public_folder: ""

media_libraries:
  default:
    config:
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
          width: 2048 # default: original size
          height: 2048 # default: original size
        svg:
          optimize: true

slug:
  clean_accents: true
  sanitize_replacement: "-"
editor:
  preview: true

# ::: Collection Recettes
#
collections:
  - name: "recettes"
    label: "Recettes"
    label_singular: "Recette"
    icon: chef_hat
    folder: "content/recettes/"
    path: "{{type}}/{{slug}}/index"
    slug: "{{title}}_{{uuid_short}}"
    filter: { field: "layout", value: "recettes" }
    description: "Liste de l'ensemble des recettes. Vous pouvez utiliser les filtres ci-dessous pour classer / filtrer les recettes."
    sortable_fields: ["title", "publishDate"]

    view_filters:
      - label: "Brouillons"
        field: draft
        pattern: true
      - label: "plats"
        field: type
        pattern: "plat"
      - label: "entrées"
        field: type
        pattern: "entree"
      - label: "desserts"
        field: type
        pattern: "desserts"
      - label: "non testé"
        field: check
        pattern: "Non"

    view_groups:
      default: draft
      groups:
      - label: "Catégorie: "
        field: type
      - label: "Sous-catégories: "
        field: categories
      - label: "Auteur·es: "
        field: auteur
      - label: "Cuisson: "
        field: cuisson
      - label: "Sevice chaud/froid: "
        field: temperature
      - label: "Brouillons"
        name: draft
        field: draft

    summary: "{{title}} ({{type}} - {{auteur}})"

    create: true

    fields:
      # - {name: "info", widget: "text-info", default: "Ceci est un exemple de texte d'information pour les utilisateurs.", required: false}

      - {
          label: "Intitulé",
          name: "title",
          widget: "string",
          hint: "Ne peut contenir que des lettres, des chiffres, des parenthèses ou des tirets (-)",
          pattern:
            [
              '^[a-zA-Z0-9 éèëïïùàâôêûç \u002C\u0027\u2018\u2019\u00C0-\u00FF()\-]+$',
              "Contient un caractère spécial interdit. Ne peut contenir que des lettres, des chiffres, des parenthèses ou des tirets (-), virgules et apostrophes.",
            ],
        }
      - { label: "Brouillon", name: "draft", widget: "boolean", default: false, required: false, hint: "Les brouillons ne sont pas publiés." }
      - {
          label: "Image",
          name: "img",
          widget: "image",
          required: false,
          allow_multiple: false,
        }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "recettes",
        }
      - label: "Catégorie"
        name: "type"
        widget: "select"
        options:
          - { label: "Entrée", value: "entree" }
          - { label: "Plat", value: "plat" }
          - { label: "Dessert", value: "dessert" }
      - label: "Sous-catégories"
        name: "categories"
        widget: "relation"
        collection: "sous-categories"
        value_field: "title"
        search_fields: ["title"]
        multiple: true
        max: 4
        options_length: 50
        required: true
        hint: "Vous pouvez en définir plusieurs, mais la première servira à définir l'icone associée à la recette."
      - label: "auteur"
        name: "auteur"
        widget: "string"
        required: false

        ## ::: __Description ##

      - {
          label: "Spécialité (région)",
          name: "region",
          widget: "string",
          required: false,
        }
      - label: "Saison"
        name: "saison"
        widget: "select"
        multiple: true
        required: false
        options:
          - { label: "Printemps", value: "printemps" }
          - { label: "Eté", value: "ete" }
          - { label: "Automne", value: "automne" }
          - { label: "Hiver", value: "hiver" }
      - label: "Cuisson"
        name: "cuisson"
        widget: "select"
        required: true
        options: ["Oui", "Non"]
      - label: "Température de service"
        name: "temperature"
        widget: "select"
        required: true
        options: ["Chaud", "Froid"]
      - label: "Quantités indiquées prévues pour combien de couverts ?"
        name: "plate"
        widget: "number"
        min: 1
        value_type: "int"
      - label: "Précision quantité"
        name: "quantite_desc"
        widget: "string"
        required: false
        hint: "vous pouvez préciser ici comment sont pensées les quantité. Par ex. : '24 parts par gastro'; '2 nems par personnes', etc."
      - label: "Testé ?"
        name: "check"
        hint: "Indiquez si vous avez testé la recette pour le nombre de couverts indiqués. C'est mieux si c'est le cas :)"
        widget: "select"
        options: ["Oui", "Non"]
      # - label: "Proportions fixes ?"
      #   name: "checkAlwaysOk"
      #   widget: "boolean"
      #   required: false
      #   default: false
      #   hint: "Cochez cette case si les proportions ne changent jamais, quelque-soit le nombre de couvert (par exemple pour les cakes, les tartes, et autres préparations réalisées dans des plats individuels) → Désactive les alertes qui s'affichent en cas de différences significatives entre les quantités d'ingrédients indiquées dans la recette initiale et le nombre de couvert demandé."
      # - label: "Testé aussi pour ce nombres de couverts : "
      #   name: "checkfor"
      #   widget: "number"
      #   min: 1
      #   value_type: "int"
      #   hint: "Si vous avez testé la recette pour un nombre de couverts significativement différent, et que la recette était réussie, indiquez ce nombre de couverts ici. S'il vous a fallu modifier les quantités d'ingrédients pour obtenir un résultat satisfaisant, vous pouvez 'dupliquer' cette recette (bouton 'publish' en haut → 'duplicate'), et modifier en conséquence la recette dupliquée (et amender le titre). Merci d'indiquer sur l'une des 2 recettes qu'il existe une recette alternative (compléter le champ 'Préparations Alternatives' en bas de cette page). À défaut, vous pouvez indiquer brièvement les modifications à apporter dans le champ 'astuces' en bas de cette page."
      #   required: false

      ################################
      ## ::: __Ingredients de la recette ##

      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        min: 1
        allow_add: true
        add_to_top: true
        label_singular: "Ingrédient"
        required: false
        collapsed: true
        summary: "{{fields.ingredient}}: {{fields.quantite}} {{fields.unit}}"
        fields:
          - label: "Ingrédient"
            name: ingredient
            widget: "relation"
            collection: "ingredients_index"
            search_fields: ["title"]
            display_fields: ["title"]
          - label: "Quantité (nombre)"
            name: quantite
            widget: number
            min: 0.1
            value_type: float
          - label: "Unité (quantité en...)"
            name: unit
            widget: select
            options: ["Kg", "grammes", "unité", "litre", "ml", "c. à soupe", "c. à café", "pincées", "tête·s", "gousse·s", "bottes"]
          - label: "commentaire"
            name: commentaire
            widget: string
            required: false
            hint: "Si vous avez quelque-chose à préciser... S'affiche à coté de l'ingrédients dans la recette. ⚠ Ne sera pas affiché dans les listes de course"

      ### ::: Materiel
      - label: "Materiel"
        name: "materiel"
        widget: "relation"
        collection: "materiel"
        required: false
        multiple: true
        value_field: "title"
        search_fields: ["title"]
        options_length: 30

      ### ::: Preparation
      - label: "Préparation"
        name: "preparation"
        widget: "markdown"
        editor_components: [""]


      - label: "Préparation - A Faire la veille"
        name: "preparation24h"
        widget: "markdown"
        editor_components: [""]
        required: false
        hint: "Si la recette implique de préparer des choses en avance, le préciser ici pour que ce soit mis en avant lors de l'affichage des recettes (ce sera indiquer 'A prévoir a l'avance', à vous de préciser plus précisément quand)."


      ### ::: Astuces
      - label: "Astuces"
        name: "astuces"
        widget: "list"
        allow_add: true
        add_to_top: true
        label_singular: "astuce"
        required: false
        allow_reorder: true
        fields:
          - label: "Astuce"
            name: "astuce"
            widget: "string"

      ### ::: PrepAlt
      - label: "Préparations Alternatives"
        name: "prepAlt"
        label_singular: "Préparation alternative"
        widget: "list"
        allow_add: true
        collapsed: false
        required: false
        add_to_top: true
        hint: "Si elles existent, signalez ici les recettes alternatives à celle-ci pour des régimes particuliers (végan, sans gluten, etc.); ou pour un nombres de couverts significativement différents (nécessitant des proportions d'ingrédients différents)."
        fields:
          - {
              label: "recettes",
              name: "recetteAlt",
              widget: "relation",
              collection: "recettes",
              display_fields: ["title"],
            }

      - label: "Date de publication"
        name: "publishDate"
        widget: "hidden"
        default: "{{datetime}}"


  ###############################
  ################################

  # ::: Menu / Evenements

  - label: "Evenements"
    label_singular: "Evenement"
    name: "evenement"
    icon: calendar_month
    description: "Pour créer des menus sur un ou plusieurs jours..."
    folder: content/evenements/
    path: "{{slug}}/index"
    slug: "{{title}}_{{uuid_shorter}}"
    create: true
    sortable_fields:
      fields: ["title", "publishDate"]
      defaults:
        field: publishDate
        direction: descending
    fields:
      - {
          label: "Nom de l'évènement",
          name: "title",
          widget: "string",
          hint: " Ne peut contenir que des lettres, des chiffres, des parenthèses, des tirets (-), virgules et apostrophes",
          pattern:
            [
              '^[a-zA-Z0-9 éèëïïùàâôêûç \u002C\u0027\u2018\u2019\u00C0-\u00FF()\-]+$',
              "Contient un caractère spécial interdit. Ne peut contenir que des lettres, des chiffres, des parenthèses ou des tirets (-), virgules et apostrophes.",
            ],
        }

      - { name: "sitemap_exclude", widget: "hidden", default: "true" }

      - label: "Repas"
        name: "repas"
        widget: "list"
        allow_add: true
        add_to_top: true
        collapsed: true
        allow_reorder: true
        summary: "{{fields.date_service | date('DD/MM/YYYY')}} : {{fields.horaire}} ({{fields.assiettes}} p.)"
        hint: "Ajouter un menu pour un service"

        fields:
          - {
              label: "Date",
              name: "date_service",
              widget: "datetime",
              hint: "Jour ou le repas sera servis..",
              dateFormat: YYYY-MM-DD,
            }

          - {
              label: "Horaire",
              name: "horaire",
              widget: "select",
              options: ["matin", "midi", "soir"],
            }

          - {
              label: "Nombres d'assiettes",
              name: "assiettes",
              widget: "number",
              default: 100,
              valueType: "int",
              min: 1,
              max: 10000,
            }

          - label: "Recettes du repas"
            name: "recettes_du_repas"
            widget: "list"
            allow_add: true
            add_to_top: true
            collapsed: true
            allow_reorder: true
            summary: "{{recette}} : {{fields.type_plat}} - {{fields.altAssiettes}}"
            fields:
              - label: "Recette"
                name: "recette"
                widget: "relation"
                collection: "recettes"
                value_field: ["slug"]
                search_fields: ["title"]
                display_fields: ["title"]

              - label: "Entrées/Plats/Desserts ?"
                name: "type_plat"
                widget: "select"
                options:
                  - { label: "Entrée", value: "entree" }
                  - { label: "Plat", value: "plat" }
                  - { label: "Dessert", value: "dessert" }


              - {
                  label: "Nombre d'assiettes pour cette recette",
                  name: "altAssiettes",
                  widget: "number",
                  min: 1,
                  value_type: "int",
                  max: 90000,
                  required: false,
                  hint: "Laisser vide si égale au nombre d'assiettes défini plus haut. Ce champs peut être utile pour les recettes destinées aux régimes spéciaux (sans-gluten, etc.), dont le nombre d’assiettes prévues est différent de celui défini globalement pour le repas.",
                }

              - {
                  label: "Responsable/Chef.fe cuistot",
                  name: "chef",
                  widget: "string",
                  hint: "Si il y a un.e ou des référent.es pour cette recette...",
                  required: false,
                }

              - {
                  label: "Recette lié à un plat",
                  name: "partof",
                  widget: "string",
                  hint: "Si cette recette fait partie d'un plat comportant plusieurs recettes, vous pouvez préciser ici le nom du plat afin qu'il soit visible sur les fiches recettes (et faire de même sur toutes les recettes du plat.)",
                  required: false,
                }

              # - label: "Inclure les recettes alternatives pour les régimes spéciaux (végan, sans gluten...) si elles existent"
              #   name: "includeRecetteAlt"
              #   widget: "boolean"
              #   required: true
              #   default: false
              #   hint: "Il n'est pas recommandé d'inclure les recettes alternative: il s'agit de alternatives présentes au sein des recettes. Or, pour que le calcul des quantités (pour les courses, et pour le nombre d'assiètes a servir) dans les pages 'évènements' soit clair, il vaut mieux créer une autre recette dédié. Il vaut donc mieux insérer directement cette recette dans le menu, en précisant le nombre d'assietes souhaitées."

              - {
                  label: "Commentaire",
                  name: "commentaire",
                  widget: "text",
                  hint: "Si vous avez quelque-chose a préciser...(N'oubliez pas que les pages des menus seront publié en ligne !)",
                  required: false,
                }

  - divider: true
  ################################

  # ::: Ingredients

  - name: "ingredients_index"
    label: "Ingrédients"
    icon: grocery
    description: "Liste des ingrédients disponibles pour les recettes."
    folder: "content/ingredients"
    create: true
    path: "{{slug}}/index"
    slug: "{{title}}_{{uuid_short}}"
    fields:
      - { label: "Nom de l'ingrédient", name: "title", widget: "string" }
      - label: "Type d'ingrédient"
        name: "type"
        widget: "select"
        required: true
        options:
          - { label: "Ingrédients Frais (beurre, yaourt, fromage...)", value: "frais" }
          - { label: "Fruits et Légumes (frais, secs, en conserves...)", value: "legumes" }
          - { label: "LOF : Lait, oeuf, farines, huile...", value: "lof" }
          - { label: "Sucrés (Miel, biscuits, jus de fruits, chocolats...)", value: "sucres" }
          - { label: "Assaisonnements (Epices, aromatiques, vinaigres, sauces, coulis...)", value: "epices" }
          - { label: "Sec (Légumineuses, céréales)", value: "sec" }
          - { label: "Viandes et Poissons (et crustacés, mollusques...)", value: "animaux" }
          - { label: "Autres (ce qui ne se trouve pas ailleurs...)", value: "autres" }
      - label: "Allergènes"
        name: "allergenes"
        widget: "select"
        multiple: true
        required: false
        hint: "Y compris 'alcool', 'porc', 'Non-Vegan', ou 'Vérifier l'emballage'... Permettra aussi de classer les recettes utilisant cet ingrédients comme 'vegan', 'sans-lacose', 'sans-gluten', etc."
        options:
          [ "Non-Vegan",
          "Produit Laitier",
          "Gluten",
          "Crustacé",
          "Oeuf",
          "Poisson",
          "Porc",
          "Arachides",
          "Soja",
          "Fruits à coque",
          "Céleri",
          "Moutarde",
          "Sésame",
          "Sulfites",
          "Lupin",
          "Mollusque",
          "Alcool",
          "Vérifiez l'emballage"]


      - { label: "Produit Frais ?", name: "pFrais", widget: "boolean", required: false, hint: "Fruits et légumes frais (ni surgelé, ni conserve, ni séché, etc.), ou ingrédients qui se conserve au frigo" }

      - { label: "Produit Surgelé ?", name: "pSurgel", widget: "boolean", required: false, hint: "Ingrédients qui se conserve au congélateur" }


  # ::: COLLECTION : Materiel

  - label: "Materiel"
    name: "materiel"
    icon: microwave_gen
    folder: content/materiel
    create: true
    path: "{{slug}}/index"
    url: "{{slug}}"
    widget: "list"
    fields:
      - name: "title"
        label: "Nom"
        widget: "string"
        hint: "Ne peut contenir que des lettres, des chiffres, des parenthèses, des tirets (-), virgules et apostrophes"
        pattern:
          [
            '^[a-zA-Z0-9 éèëïïùàâôêûç \u002C\u0027\u2018\u2019\u00C0-\u00FF()\-]+$',
            "Contient un caractère spécial interdit. Ne peut contenir que des lettres, des chiffres, des parenthèses ou des tirets (-), virgules et apostrophes.",
          ]
      - name: "sitemap_exclude"
        widget: "hidden"
        default: "true"

  ###########################

  # ::: Categories collections
  - label: "sous-catégorie (recettes)"
    name: "sous-categories"
    icon: yoshoku
    folder: content/categories/
    path: "{{slug}}/index"
    url: "{{slug}}"
    create: true
    widget: "list"
    fields:
      - {
          label: "Nom",
          name: "title",
          widget: "string",
          hint: "Ne peut contenir que des lettres, des chiffres, des parenthèses, des tirets (-), virgules et apostrophes",
          pattern:
            [
              '^[a-zA-Z0-9 éèëïïùàâôêûç \u002C\u0027\u2018\u2019\u00C0-\u00FF()\-]+$',
              "Contient un caractère spécial interdit. Ne peut contenir que des lettres, des chiffres, des parenthèses ou des tirets (-), virgules et apostrophes.",
            ],
        }
