import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts hugo-cookbook-theme/svelte-app/src/lib/types`.

export enum Status {
    CREATING = "creating",
    ACTIVE = "active",
    FAILED = "failed",
    ARCHIVE = "archive"
}

export type InscriptionCampaigns = Models.Row & {
    campaign_id: string;
    team_id: string;
    max_inscriptions: number;
    current_count: number;
    expires_at: string | null;
    is_active: boolean;
}

export type ListSnapshots = Models.Row & {
    listId: string;
    snapshotData: string;
    createdBy: string;
    description: string;
}

export type Main = Models.Row & {
    name: string;
    createdBy: string;
    isActive: boolean;
    originalDataHash: string;
    dateStart: string | null;
    dateEnd: string | null;
    teams: string[] | null;
    status: Status | null;
    error: string | null;
}

export type Products = Models.Row & {
    productHugoUuid: string;
    productName: string;
    productType: string;
    pFrais: boolean;
    pSurgel: boolean;
    stockReel: string | null;
    mainId: Main;
    status: string;
    who: string[] | null;
    store: string | null;
    previousNames: string[] | null;
    isMerged: boolean;
    mergedInto: string | null;
    mergedFrom: string[] | null;
    mergeDate: string | null;
    mergeReason: string | null;
    nbRecipes: number | null;
    totalAssiettes: number | null;
    dateTimeService: string | null;
    recipeNames: string | null;
    totalNeededConsolidated: string | null;
    totalNeededRaw: string | null;
    conversionRules: string[] | null;
    recipesOccurrences: string | null;
    neededConsolidatedByDate: string | null;
    purchases: Purchases[];
}

export type Purchases = Models.Row & {
    mainId: Main;
    unit: string;
    store: string | null;
    status: string | null;
    notes: string;
    price: number | null;
    quantity: number;
    who: string | null;
    createdBy: string | null;
    products: Products[];
}
