import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts ../hugo-cookbook-theme/svelte-app/src/lib/types`.

export enum MainStatus {
    ARCHIVE = "archive",
    LOCKED = "locked",
    PROPOSITION = "proposition",
    CONFIRMED = "confirmed",
    CANCELED = "canceled"
}

export enum RecettesTypeR {
    ENTREE = "entree",
    PLAT = "plat",
    DESSERT = "dessert",
    AUTRE = "autre"
}

export enum RecettesStatus {
    PUBLIC = "public",
    PRIVATE = "private",
    DELETED = "deleted"
}

export enum MaterielType {
    ELECTRONIC = "electronic",
    MANUAL = "manual",
    OTHER = "other",
    TOOLS = "tools",
    DISH = "dish"
}

export enum MaterielStatus {
    OK = "ok",
    LOST = "lost",
    LOAN = "loan",
    RESERVED = "reserved",
    TOREPAIR = "torepair"
}

export enum UserNotificationsNotificationType {
    TEAM_ACCESS_GRANTED = "team_access_granted",
    EVENT_ACCESS_GRANTED = "event_access_granted"
}

export enum EventTodoPriority {
    LOW = "low",
    MEDIUM = "medium",
    HIGH = "high"
}

export enum EventTodoStatus {
    TODO = "todo",
    DONE = "done",
    WAITING = "waiting",
    CANCELED = "canceled",
    INPROGRESS = "inprogress"
}

export enum EventTodoTaskOn {
    BEFORE_EVENT = "beforeEvent",
    ON_EVENT = "onEvent",
    AFTER_EVENT = "afterEvent"
}

export type InscriptionCampaigns = Models.Row & {
    campaign_id: string;
    team_id: string;
    max_inscriptions: number;
    current_count: number;
    expires_at: string | null;
    is_active: boolean;
}

export type ListSnapshots = Models.Row & {
    listId: string;
    snapshotData: string;
    createdBy: string;
    description: string;
}

export type Main = Models.Row & {
    name: string;
    createdBy: string;
    isActive: boolean;
    originalDataHash: string | null;
    dateStart: string | null;
    dateEnd: string | null;
    teams: string[] | null;
    status: MainStatus | null;
    error: string | null;
    allDates: string[] | null;
    productsId: Products[];
    purchasesId: Purchases[];
    contributors: string[] | null;
    kteams: Kteams[];
    meals: string[] | null;
    contributorsIds: string[] | null;
    description: string | null;
    minContrib: number;
}

export type Products = Models.Row & {
    productHugoUuid: string | null;
    productName: string;
    stockReel: string | null;
    status: string;
    who: string[] | null;
    store: string;
    previousNames: string[] | null;
    isMerged: boolean;
    mergedFrom: string[] | null;
    mergeDate: string | null;
    mergeReason: string | null;
    purchases: Purchases[];
    isSynced: boolean;
    mergedInto: string | null;
    mainId: Main;
    totalNeededOverride: string | null;
    updatedBy: string | null;
    productType: string | null;
    specs: string | null;
}

export type Purchases = Models.Row & {
    unit: string;
    store: string | null;
    status: string | null;
    notes: string;
    price: number | null;
    quantity: number;
    who: string | null;
    createdBy: string | null;
    products: Products[];
    mainId: Main;
    orderDate: string | null;
    deliveryDate: string | null;
    invoiceId: string | null;
    invoiceTotal: number | null;
}

export type Recettes = Models.Row & {
    title: string;
    plate: number;
    preparation: string;
    draft: boolean;
    typeR: RecettesTypeR;
    categories: string[] | null;
    regime: string[] | null;
    publishedAt: string | null;
    createdBy: string;
    teams: string[] | null;
    materiel: string[] | null;
    prepAlt: string[] | null;
    ingredients: string[] | null;
    description: string | null;
    region: string | null;
    cuisson: boolean;
    quantite_desc: string | null;
    check: boolean;
    preparation24h: string | null;
    permissionWrite: string[] | null;
    serveHot: boolean;
    lockedBy: string | null;
    saison: string[] | null;
    auteur: string | null;
    astuces: string[] | null;
    status: RecettesStatus;
    rootRecipeId: string | null;
    versionLabel: string | null;
}

export type Kteams = Models.Row & {
    name: string;
    description: string | null;
    members: string[];
    invited: string[] | null;
    main: Main[];
    department: string | null;
    isPublic: boolean;
}

export type Materiel = Models.Row & {
    description: string | null;
    type: MaterielType | null;
    quantity: number;
    name: string;
    location: string | null;
    loan: string[] | null;
    shareableWith: string[] | null;
    status: MaterielStatus;
    owner: string | null;
}

export type Locks = Models.Row & {
    userId: string;
    userName: string;
    expiresAt: string;
}

export type UserNotifications = Models.Row & {
    notificationType: UserNotificationsNotificationType;
    targetCollection: string | null;
    targetDocumentId: string | null;
    userId: string;
}

export type EventTodo = Models.Row & {
    taskId: string;
    eventId: string;
    taskName: string;
    taskDescription: string | null;
    dueDate: string | null;
    priority: EventTodoPriority | null;
    status: EventTodoStatus | null;
    taskOn: EventTodoTaskOn | null;
    requiredPeopleNb: number;
    locked: boolean;
    assignedTo: string[] | null;
}
